"""Ad model changes

Revision ID: ef5f0c078b5f
Revises: 58e9d78a46a2
Create Date: 2025-04-23 22:10:11.982940

"""
import random
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5f0c078b5f'
down_revision: Union[str, None] = '58e9d78a46a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('price', sa.Integer(), nullable=True))

    op.add_column('ad', sa.Column('latitude', sa.Numeric(precision=7, scale=4), nullable=True))
    op.execute(f"UPDATE ad SET latitude = {round(random.uniform(-90, 90), 6)} WHERE latitude IS NULL")
    op.alter_column('ad', 'latitude', nullable=False)
    op.add_column('ad', sa.Column('longitude', sa.Numeric(precision=7, scale=4), nullable=True))
    op.execute(f"UPDATE ad SET longitude = {round(random.uniform(-180, 180), 6)} WHERE longitude IS NULL")
    op.alter_column('ad', 'longitude', nullable=False)
    op.drop_column('ad', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ad', 'longitude')
    op.drop_column('ad', 'latitude')
    op.drop_column('ad', 'price')
    # ### end Alembic commands ###
