"""create ad table

Revision ID: 43e9332f2fcc
Revises: dc8fedac8410
Create Date: 2025-06-04 09:38:03.324293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43e9332f2fcc'
down_revision: Union[str, None] = 'dc8fedac8410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deal_type', sa.Enum('sale', 'rent', name='dealtype'), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('complex_name', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('house_number', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(precision=8), nullable=False),
    sa.Column('longitude', sa.Float(precision=8), nullable=False),
    sa.Column('floors_in_building', sa.Integer(), nullable=True),
    sa.Column('current_floor', sa.Integer(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('bathrooms_count', sa.Integer(), nullable=True),
    sa.Column('bedrooms_count', sa.Integer(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('kitchen_area', sa.Float(), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('commission_from_buyer', sa.Boolean(), nullable=True),
    sa.Column('contact_type', sa.Enum('realtor', 'owner', name='contacttype'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_id'), 'ad', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=True)
    op.alter_column('otp', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ad_id'), table_name='ad')
    op.drop_table('ad')
    # ### end Alembic commands ###
