"""Create user and otp tables

Revision ID: 37222f64a9f4
Revises: 118ffda30050
Create Date: 2025-04-06 13:04:04.514037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37222f64a9f4'
down_revision: Union[str, None] = '118ffda30050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_t_p',
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_o_t_p_id'), 'o_t_p', ['id'], unique=False)
    op.add_column('user', sa.Column('role', sa.String(length=5), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('phone_verified', sa.Boolean(), nullable=False))
    op.drop_index('ix_user_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_column('user', 'phone_verified')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'role')
    op.drop_index(op.f('ix_o_t_p_id'), table_name='o_t_p')
    op.drop_table('o_t_p')
    # ### end Alembic commands ###
