"""add_is_verified_to_user

Revision ID: 5bc58f2022e4
Revises: 182fbaeb3704
Create Date: 2025-09-03 16:14:07.016449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bc58f2022e4'
down_revision: Union[str, None] = '182fbaeb3704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add is_verified column as nullable first
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True, comment='User verification status'))
    
    # Set default value for existing users
    op.execute("UPDATE \"user\" SET is_verified = false WHERE is_verified IS NULL")
    
    # Make column not nullable
    op.alter_column('user', 'is_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.alter_column('ad', 'longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ad', 'latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
