"""Ad model changes

Revision ID: 71357716f7cc
Revises: ef5f0c078b5f
Create Date: 2025-04-23 22:20:36.633341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71357716f7cc'
down_revision: Union[str, None] = 'ef5f0c078b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad', 'latitude',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ad', 'longitude',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    op.alter_column('ad', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=7, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
