"""Remove is_author_verified field from Ad model

Revision ID: 4c7270538aec
Revises: 651f91cdb1e4
Create Date: 2025-09-18 20:24:36.537139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7270538aec'
down_revision: Union[str, None] = '651f91cdb1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'is_author_verified')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email address'))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.add_column('ad', sa.Column('is_author_verified', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Author verified with OneID'))
    op.alter_column('ad', 'longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ad', 'latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
