"""add user_id to OTP

Revision ID: dc8fedac8410
Revises: 951c996956e4
Create Date: 2025-04-30 10:36:23.920980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8fedac8410'
down_revision: Union[str, None] = '951c996956e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_t_p', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('o_t_p_phone_number_key', 'o_t_p', type_='unique')
    op.create_foreign_key(None, 'o_t_p', 'user', ['user_id'], ['id'])
    op.drop_column('o_t_p', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('o_t_p', sa.Column('phone_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'o_t_p', type_='foreignkey')
    op.create_unique_constraint('o_t_p_phone_number_key', 'o_t_p', ['phone_number'])
    op.drop_column('o_t_p', 'user_id')
    # ### end Alembic commands ###
