"""Add verification fields and gold verification requests

Revision ID: 651f91cdb1e4
Revises: 5bc58f2022e4
Create Date: 2025-09-18 20:13:32.369793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651f91cdb1e4'
down_revision: Union[str, None] = '5bc58f2022e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_verification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='goldverificationstatus'), nullable=False),
    sa.Column('request_reason', sa.Text(), nullable=True, comment="User's reason for requesting gold verification"),
    sa.Column('admin_comment', sa.Text(), nullable=True, comment="Admin's comment on the request"),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ad.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_verification_requests_id'), 'gold_verification_requests', ['id'], unique=False)
    op.add_column('ad', sa.Column('is_author_verified', sa.Boolean(), nullable=False, comment='Author verified with OneID'))
    op.add_column('ad', sa.Column('is_gold_verified', sa.Boolean(), nullable=False, comment='Gold verification status'))
    op.add_column('ad', sa.Column('gold_verification_status', sa.Enum('pending', 'approved', 'rejected', name='goldverificationstatus'), nullable=False))
    op.add_column('ad', sa.Column('gold_verification_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ad', sa.Column('gold_verification_processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ad', sa.Column('gold_verification_comment', sa.Text(), nullable=True, comment='Admin comment for gold verification'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email address'))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('ad', 'longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ad', 'latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('ad', 'gold_verification_comment')
    op.drop_column('ad', 'gold_verification_processed_at')
    op.drop_column('ad', 'gold_verification_requested_at')
    op.drop_column('ad', 'gold_verification_status')
    op.drop_column('ad', 'is_gold_verified')
    op.drop_column('ad', 'is_author_verified')
    op.drop_index(op.f('ix_gold_verification_requests_id'), table_name='gold_verification_requests')
    op.drop_table('gold_verification_requests')
    # ### end Alembic commands ###
