"""increase user.role length

Revision ID: 030da56db355
Revises: 60dd0fceb76f
Create Date: 2026-01-12 18:19:18.590281

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "030da56db355"
down_revision: Union[str, None] = "60dd0fceb76f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "role",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "role",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=5),
        existing_nullable=False,
    )
    op.alter_column(
        "ad",
        "longitude",
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "ad",
        "latitude",
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
