"""add_realtor_role_avatar_company_views

Revision ID: 60dd0fceb76f
Revises: a1dca200e24d
Create Date: 2026-01-11 23:12:21.286611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dd0fceb76f'
down_revision: Union[str, None] = 'a1dca200e24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add views_count column as nullable first
    op.add_column('ad', sa.Column('views_count', sa.Integer(), nullable=True, comment='Number of times the ad has been viewed'))
    # Update existing rows to 0
    op.execute("UPDATE ad SET views_count = 0 WHERE views_count IS NULL")
    # Make it NOT NULL
    op.alter_column('ad', 'views_count', nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Email address'))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'avatar')
    op.alter_column('ad', 'longitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ad', 'latitude',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('ad', 'views_count')
    # ### end Alembic commands ###
