"""one_id delete set to cascade in user_id

Revision ID: 15cd923eced5
Revises: 030da56db355
Create Date: 2026-01-12 18:41:50.321936

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15cd923eced5"
down_revision: Union[str, None] = "030da56db355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("one_id_info_user_id_fkey", "one_id_info", type_="foreignkey")
    op.create_foreign_key(
        None, "one_id_info", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "one_id_info", type_="foreignkey")
    op.create_foreign_key(
        "one_id_info_user_id_fkey", "one_id_info", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "ad",
        "longitude",
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    op.alter_column(
        "ad",
        "latitude",
        existing_type=sa.Float(precision=8),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
